version: '3.5'

services:

#  app:
#    build: .
#    restart: always
#    depends_on:
#      - db
#    command: python main.py bot
#    networks:
#      - default
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#
#  scheduler:
#    build: .
#    restart: always
#    depends_on:
#      - db
#    command: python main.py prizm_check_scheduler
#    networks:
#      - default
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  db:
    image: postgres:13
    restart: always
    ports:
      - "5438:5432"
    volumes:
      - prizm_bot_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lQ1IEcHimk9aWKV
      - POSTGRES_DB=prizm_p2p_bot_db

    networks:
      - default

  redis:
    image: redis
    ports:
      - "6392:6379"
    volumes:
      - redis_data:/data
    command: >
      --requirepass lQ1IEcHimk9aWKV
    networks:
      - default

volumes:
  redis_data: { }
  prizm_bot_db: { }
