"""add column user.online

Revision ID: 00d0a390c989
Revises: f532127a53b2
Create Date: 2025-03-20 16:21:30.333366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d0a390c989'
down_revision = 'f532127a53b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_online', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_online')
    # ### end Alembic commands ###
