"""settings

Revision ID: 04535483f54a
Revises: 20519a7d7d91
Create Date: 2025-02-26 16:07:45.960601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04535483f54a'
down_revision = '20519a7d7d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_wait_minutes', sa.BigInteger(), nullable=True),
    sa.Column('pay_wait_time', sa.BigInteger(), nullable=True),
    sa.Column('commission_percent', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
