"""update date without timezone

Revision ID: 094d1376bf5b
Revises: 3a0a51e95278
Create Date: 2025-03-07 13:10:02.322425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094d1376bf5b'
down_revision = '3a0a51e95278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit_rub', 'max_limit_rub'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit', 'max_limit'], unique=False)
    # ### end Alembic commands ###
