"""update date without timezone

Revision ID: 1293ff46a279
Revises: 094d1376bf5b
Create Date: 2025-03-07 13:10:43.854414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1293ff46a279'
down_revision = '094d1376bf5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
