"""settings update

Revision ID: 24ab8b831c31
Revises: da22eb6ad74b
Create Date: 2025-04-03 12:46:11.843791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24ab8b831c31'
down_revision = 'da22eb6ad74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'commission_percent',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=3, asdecimal=False),
               existing_nullable=False)
    op.alter_column('settings', 'withdrawal_commission_percent',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=3, asdecimal=False),
               nullable=False)
    op.alter_column('settings', 'prizm_rate_diff',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=3, asdecimal=False),
               existing_nullable=False)
    op.alter_column('settings', 'partner_commission_percent',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=3, asdecimal=False),
               existing_nullable=True)
    op.alter_column('settings', 'minimum_referal_withdrawal_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=3, asdecimal=False),
               existing_nullable=True)
    op.alter_column('settings', 'min_order_prizm_value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=3, asdecimal=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'min_order_prizm_value',
               existing_type=sa.Numeric(precision=18, scale=3, asdecimal=False),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('settings', 'minimum_referal_withdrawal_amount',
               existing_type=sa.Numeric(precision=18, scale=3, asdecimal=False),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('settings', 'partner_commission_percent',
               existing_type=sa.Numeric(precision=18, scale=3, asdecimal=False),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('settings', 'prizm_rate_diff',
               existing_type=sa.Numeric(precision=18, scale=3, asdecimal=False),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('settings', 'withdrawal_commission_percent',
               existing_type=sa.Numeric(precision=18, scale=3, asdecimal=False),
               type_=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('settings', 'commission_percent',
               existing_type=sa.Numeric(precision=18, scale=3, asdecimal=False),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
