"""update

Revision ID: 25db8940ec4c
Revises: 9aa293505d94
Create Date: 2025-03-23 12:55:48.582560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25db8940ec4c'
down_revision = '9aa293505d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_between', 'order_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('wallet', sa.Column('order_id', sa.BigInteger(), nullable=True))
    op.add_column('wallet', sa.Column('order_request_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_wallet_order_id'), 'wallet', ['order_id'], unique=False)
    op.create_index(op.f('ix_wallet_order_request_id'), 'wallet', ['order_request_id'], unique=False)
    op.create_foreign_key(None, 'wallet', 'order', ['order_id'], ['id'])
    op.create_foreign_key(None, 'wallet', 'order_request', ['order_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_index(op.f('ix_wallet_order_request_id'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_order_id'), table_name='wallet')
    op.drop_column('wallet', 'order_request_id')
    op.drop_column('wallet', 'order_id')
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('message_between', 'order_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
