"""update settings

Revision ID: 345597c5748f
Revises: 82bd70df46f0
Create Date: 2025-03-06 21:40:28.052012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345597c5748f'
down_revision = '82bd70df46f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('prizm_rate_diff', sa.Integer(), nullable=True))
    op.alter_column('settings', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('settings', 'order_wait_minutes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('settings', 'pay_wait_time',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('settings', 'commission_percent',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Integer(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'commission_percent',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('settings', 'pay_wait_time',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('settings', 'order_wait_minutes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('settings', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('settings', 'prizm_rate_diff')
    # ### end Alembic commands ###
