"""transaction fix

Revision ID: 36056a3bc6dc
Revises: f39c84e2c0c3
Create Date: 2025-03-10 11:33:45.559432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36056a3bc6dc'
down_revision = 'f39c84e2c0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit_rub', 'max_limit_rub'], unique=False)
    op.drop_constraint('transaction_order_request_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_order_id_fkey', 'transaction', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transaction_order_id_fkey', 'transaction', 'order', ['order_id'], ['id'])
    op.create_foreign_key('transaction_order_request_id_fkey', 'transaction', 'order_request', ['order_request_id'], ['id'])
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit', 'max_limit'], unique=False)
    # ### end Alembic commands ###
