"""update date without timezone

Revision ID: 3a0a51e95278
Revises: 1fb2467c77fc
Create Date: 2025-03-07 13:09:08.877210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0a51e95278'
down_revision = '1fb2467c77fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
