"""refactor+message_between

Revision ID: 4ce38c94fa07
Revises: 36056a3bc6dc
Create Date: 2025-03-20 21:26:58.720707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce38c94fa07'
down_revision = '36056a3bc6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_between',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('from_user_id', sa.BigInteger(), nullable=True),
    sa.Column('to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.String(length=4096), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('document', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_between_created_at'), 'message_between', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_between_from_user_id'), 'message_between', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_message_between_order_id'), 'message_between', ['order_id'], unique=False)
    op.create_index(op.f('ix_message_between_to_user_id'), 'message_between', ['to_user_id'], unique=False)
    op.drop_constraint('order_to_currency_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_from_currency_fkey', 'order', type_='foreignkey')
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit', 'max_limit'], unique=False)
    op.drop_constraint('order_request_to_currency_fkey', 'order_request', type_='foreignkey')
    op.drop_constraint('order_request_from_currency_fkey', 'order_request', type_='foreignkey')
    op.drop_constraint('transfer_currency_fkey', 'transfer', type_='foreignkey')
    op.add_column('user', sa.Column('last_online', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_constraint('wallet_currency_fkey', 'wallet', type_='foreignkey')
    op.drop_table('currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('wallet_currency_fkey', 'wallet', 'currency', ['currency'], ['id'])
    op.drop_column('user', 'last_online')
    op.create_foreign_key('transfer_currency_fkey', 'transfer', 'currency', ['currency'], ['id'])
    op.create_foreign_key('order_request_from_currency_fkey', 'order_request', 'currency', ['from_currency'], ['id'])
    op.create_foreign_key('order_request_to_currency_fkey', 'order_request', 'currency', ['to_currency'], ['id'])
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit_rub', 'max_limit_rub'], unique=False)
    op.create_foreign_key('order_from_currency_fkey', 'order', 'currency', ['from_currency'], ['id'])
    op.create_foreign_key('order_to_currency_fkey', 'order', 'currency', ['to_currency'], ['id'])
    op.create_table('currency',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='currency_pkey')
    )
    op.drop_index(op.f('ix_message_between_to_user_id'), table_name='message_between')
    op.drop_index(op.f('ix_message_between_order_id'), table_name='message_between')
    op.drop_index(op.f('ix_message_between_from_user_id'), table_name='message_between')
    op.drop_index(op.f('ix_message_between_created_at'), table_name='message_between')
    op.drop_table('message_between')
    # ### end Alembic commands ###
