"""wallet fix

Revision ID: 5b6908c7daeb
Revises: f0481e2c864d
Create Date: 2025-02-25 16:13:01.309471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6908c7daeb'
down_revision = 'f0481e2c864d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_request_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('order_order_request_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'order_request', ['order_request_id'], ['id'])
    op.drop_column('order', 'order_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_request', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_order_request_fkey', 'order', 'order_request', ['order_request'], ['id'])
    op.drop_column('order', 'order_request_id')
    # ### end Alembic commands ###
