"""update orders

Revision ID: 5ff6e8b830ae
Revises: a501d2fc8b55
Create Date: 2025-03-05 02:09:58.527379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff6e8b830ae'
down_revision = 'a501d2fc8b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit_rub', 'max_limit_rub'], unique=False)
    op.add_column('transaction', sa.Column('order_request_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_transaction_order_request_id'), 'transaction', ['order_request_id'], unique=False)
    op.create_foreign_key(None, 'transaction', 'order_request', ['order_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_order_request_id'), table_name='transaction')
    op.drop_column('transaction', 'order_request_id')
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit', 'max_limit'], unique=False)
    # ### end Alembic commands ###
