"""channels posting update

Revision ID: 70a77202773b
Revises: 7f1b461342c1
Create Date: 2025-04-16 19:44:51.755032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70a77202773b'
down_revision = '7f1b461342c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_channel', sa.Column('is_stopped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_channel', 'is_stopped')
    # ### end Alembic commands ###
