"""new settings

Revision ID: 74b352b640c4
Revises: c475332820ee
Create Date: 2025-03-27 17:05:17.747254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74b352b640c4'
down_revision = 'c475332820ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('min_order_prizm_value', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'min_order_prizm_value')
    # ### end Alembic commands ###
