"""channels update

Revision ID: 7f1b461342c1
Revises: 8199bdb83bd4
Create Date: 2025-04-16 10:07:33.643049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f1b461342c1'
down_revision = '8199bdb83bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_channel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('is_bot_admin', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('count_in_day', sa.Integer(), nullable=True),
    sa.Column('interval_in_day', sa.String(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('last_post', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_channel_created_at'), 'chat_channel', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_channel_last_post'), 'chat_channel', ['last_post'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_channel_last_post'), table_name='chat_channel')
    op.drop_index(op.f('ix_chat_channel_created_at'), table_name='chat_channel')
    op.drop_table('chat_channel')
    # ### end Alembic commands ###
