"""settings update 

Revision ID: 82bd70df46f0
Revises: 5ff6e8b830ae
Create Date: 2025-03-06 09:53:20.193887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bd70df46f0'
down_revision = '5ff6e8b830ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit', 'max_limit'], unique=False)
    op.alter_column('settings', 'commission_percent',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'commission_percent',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.BIGINT(),
               nullable=True)
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit_rub', 'max_limit_rub'], unique=False)
    # ### end Alembic commands ###
