"""wallet order_id order_request_id

Revision ID: 88415b7a2170
Revises: 4ce38c94fa07
Create Date: 2025-03-23 01:03:14.376176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88415b7a2170'
down_revision = '4ce38c94fa07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('order_id', sa.BigInteger(), nullable=True))
    op.add_column('wallet', sa.Column('order_request_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_wallet_order_id'), 'wallet', ['order_id'], unique=False)
    op.create_index(op.f('ix_wallet_order_request_id'), 'wallet', ['order_request_id'], unique=False)
    op.create_foreign_key(None, 'wallet', 'order_request', ['order_request_id'], ['id'])
    op.create_foreign_key(None, 'wallet', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_index(op.f('ix_wallet_order_request_id'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_order_id'), table_name='wallet')
    op.drop_column('wallet', 'order_request_id')
    op.drop_column('wallet', 'order_id')
    # ### end Alembic commands ###
