"""remove enum

Revision ID: 8b7e02705f72
Revises: a031f618e6b2
Create Date: 2025-03-19 09:21:19.021893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7e02705f72'
down_revision = 'a031f618e6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('order_to_currency_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_from_currency_fkey', 'order', type_='foreignkey')
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit', 'max_limit'], unique=False)
    op.drop_constraint('order_request_from_currency_fkey', 'order_request', type_='foreignkey')
    op.drop_constraint('order_request_to_currency_fkey', 'order_request', type_='foreignkey')
    op.drop_constraint('transfer_currency_fkey', 'transfer', type_='foreignkey')
    op.drop_constraint('wallet_currency_fkey', 'wallet', type_='foreignkey')
    op.drop_table('currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('wallet_currency_fkey', 'wallet', 'currency', ['currency'], ['id'])
    op.create_foreign_key('transfer_currency_fkey', 'transfer', 'currency', ['currency'], ['id'])
    op.create_foreign_key('order_request_to_currency_fkey', 'order_request', 'currency', ['to_currency'], ['id'])
    op.create_foreign_key('order_request_from_currency_fkey', 'order_request', 'currency', ['from_currency'], ['id'])
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit_rub', 'max_limit_rub'], unique=False)
    op.create_foreign_key('order_from_currency_fkey', 'order', 'currency', ['from_currency'], ['id'])
    op.create_foreign_key('order_to_currency_fkey', 'order', 'currency', ['to_currency'], ['id'])
    op.create_table('currency',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='currency_pkey')
    )
    # ### end Alembic commands ###
