"""settings

Revision ID: 9a31b92fa1ef
Revises: 5590e39779ae
Create Date: 2025-03-25 15:45:33.960634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a31b92fa1ef'
down_revision = '5590e39779ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('withdrawal_commission_percent', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'withdrawal_commission_percent')
    # ### end Alembic commands ###
