"""upd timezone

Revision ID: 9aa293505d94
Revises: 83e28026e628
Create Date: 2025-03-20 17:02:15.997492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa293505d94'
down_revision = '83e28026e628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
