"""remove currency

Revision ID: a031f618e6b2
Revises: 36056a3bc6dc
Create Date: 2025-03-18 19:38:27.620765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a031f618e6b2'
down_revision = '36056a3bc6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'from_currency',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RUB', 'PRIZM', name='currency'),
               existing_nullable=False)
    op.alter_column('order', 'to_currency',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RUB', 'PRIZM', name='currency'),
               existing_nullable=False)
    op.drop_constraint('order_to_currency_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_from_currency_fkey', 'order', type_='foreignkey')
    op.alter_column('order_request', 'from_currency',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RUB', 'PRIZM', name='currency'),
               existing_nullable=False)
    op.alter_column('order_request', 'to_currency',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RUB', 'PRIZM', name='currency'),
               existing_nullable=False)
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit', 'max_limit'], unique=False)
    op.drop_constraint('order_request_from_currency_fkey', 'order_request', type_='foreignkey')
    op.drop_constraint('order_request_to_currency_fkey', 'order_request', type_='foreignkey')
    op.alter_column('transfer', 'currency',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RUB', 'PRIZM', name='currency'),
               existing_nullable=False)
    op.drop_constraint('transfer_currency_fkey', 'transfer', type_='foreignkey')
    op.alter_column('wallet', 'currency',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RUB', 'PRIZM', name='currency'),
               existing_nullable=False)
    op.drop_constraint('wallet_currency_fkey', 'wallet', type_='foreignkey')
    op.drop_table('currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('wallet_currency_fkey', 'wallet', 'currency', ['currency'], ['id'])
    op.alter_column('wallet', 'currency',
               existing_type=sa.Enum('RUB', 'PRIZM', name='currency'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_foreign_key('transfer_currency_fkey', 'transfer', 'currency', ['currency'], ['id'])
    op.alter_column('transfer', 'currency',
               existing_type=sa.Enum('RUB', 'PRIZM', name='currency'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_foreign_key('order_request_to_currency_fkey', 'order_request', 'currency', ['to_currency'], ['id'])
    op.create_foreign_key('order_request_from_currency_fkey', 'order_request', 'currency', ['from_currency'], ['id'])
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit_rub', 'max_limit_rub'], unique=False)
    op.alter_column('order_request', 'to_currency',
               existing_type=sa.Enum('RUB', 'PRIZM', name='currency'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('order_request', 'from_currency',
               existing_type=sa.Enum('RUB', 'PRIZM', name='currency'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_foreign_key('order_from_currency_fkey', 'order', 'currency', ['from_currency'], ['id'])
    op.create_foreign_key('order_to_currency_fkey', 'order', 'currency', ['to_currency'], ['id'])
    op.alter_column('order', 'to_currency',
               existing_type=sa.Enum('RUB', 'PRIZM', name='currency'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('order', 'from_currency',
               existing_type=sa.Enum('RUB', 'PRIZM', name='currency'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('currency',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='currency_pkey')
    )
    # ### end Alembic commands ###
