"""update user and settings

Revision ID: bf9aef26e422
Revises: 25db8940ec4c
Create Date: 2025-03-24 09:46:45.940787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9aef26e422'
down_revision = '25db8940ec4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('partner_commission_percent', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('user', sa.Column('partner_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'partner_id')
    op.drop_column('settings', 'partner_commission_percent')
    # ### end Alembic commands ###
