"""init orders

Revision ID: c3826a29662d
Revises: 04535483f54a
Create Date: 2025-03-04 12:32:24.399544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3826a29662d'
down_revision = '04535483f54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('from_wallet_address', sa.String(), nullable=False),
    sa.Column('to_wallet_address', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('message_text', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_created_at'), 'transaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_transaction_from_wallet_address'), 'transaction', ['from_wallet_address'], unique=False)
    op.create_index(op.f('ix_transaction_order_id'), 'transaction', ['order_id'], unique=False)
    op.create_index(op.f('ix_transaction_to_wallet_address'), 'transaction', ['to_wallet_address'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_id'), 'transaction', ['transaction_id'], unique=False)
    op.add_column('order', sa.Column('mode', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'mode')
    op.drop_index(op.f('ix_transaction_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_to_wallet_address'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_order_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_from_wallet_address'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_created_at'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
