"""update orders

Revision ID: d4065dac1b08
Revises: c3826a29662d
Create Date: 2025-03-04 14:48:11.535442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4065dac1b08'
down_revision = 'c3826a29662d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_request', sa.Column('min_limit_rub', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False))
    op.add_column('order_request', sa.Column('max_limit_rub', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False))
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit_rub', 'max_limit_rub'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit', 'max_limit'], unique=False)
    op.drop_column('order_request', 'max_limit_rub')
    op.drop_column('order_request', 'min_limit_rub')
    # ### end Alembic commands ###
