"""wallet_type in order request

Revision ID: da22eb6ad74b
Revises: 74b352b640c4
Create Date: 2025-03-30 14:02:23.565612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da22eb6ad74b'
down_revision = '74b352b640c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_request', sa.Column('wallet_type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_request', 'wallet_type')
    # ### end Alembic commands ###
