"""is_wallet_activated

Revision ID: deffa1508fbd
Revises: ef9e0c762cd0
Create Date: 2025-04-17 14:51:25.404654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'deffa1508fbd'
down_revision = 'ef9e0c762cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_wallet_activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_wallet_activated')
    # ### end Alembic commands ###
