"""structure_path

Revision ID: ef9e0c762cd0
Revises: 70a77202773b
Create Date: 2025-04-17 13:41:54.638317

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef9e0c762cd0'
down_revision = '70a77202773b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree;")
    op.add_column('user', sa.Column('structure_path', sqlalchemy_utils.types.ltree.LtreeType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'structure_path')
    # ### end Alembic commands ###
