"""wallet fix

Revision ID: f0481e2c864d
Revises: 6098604253d8
Create Date: 2025-02-25 16:07:24.192250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0481e2c864d'
down_revision = '6098604253d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'value',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'value',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=18, scale=4),
               nullable=False)
    # ### end Alembic commands ###
