"""init

Revision ID: f70effe195f1
Revises: 
Create Date: 2025-02-17 13:12:29.213407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70effe195f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=True),
    sa.Column('order_count', sa.BigInteger(), nullable=True),
    sa.Column('cancel_order_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('order',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=False),
    sa.Column('to_currency', sa.String(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_currency'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_currency'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_created_at'), 'order', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_from_user_id'), 'order', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_order_to_user_id'), 'order', ['to_user_id'], unique=False)
    op.create_index('ix_seller_buyer', 'order', ['from_user_id', 'to_user_id'], unique=False)
    op.create_table('order_request',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=False),
    sa.Column('to_currency', sa.String(), nullable=False),
    sa.Column('min_limit', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('max_limit', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_currency'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['to_currency'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_from_to_currency_count', 'order_request', ['from_currency', 'to_currency', 'min_limit', 'max_limit'], unique=False)
    op.create_index(op.f('ix_order_request_created_at'), 'order_request', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_request_user_id'), 'order_request', ['user_id'], unique=False)
    op.create_table('transfer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_created_at'), 'transfer', ['created_at'], unique=False)
    op.create_index(op.f('ix_transfer_from_user_id'), 'transfer', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_transfer_to_user_id'), 'transfer', ['to_user_id'], unique=False)
    op.create_table('wallet',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_created_at'), 'wallet', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallet_user_id'), 'wallet', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_user_id'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_created_at'), table_name='wallet')
    op.drop_table('wallet')
    op.drop_index(op.f('ix_transfer_to_user_id'), table_name='transfer')
    op.drop_index(op.f('ix_transfer_from_user_id'), table_name='transfer')
    op.drop_index(op.f('ix_transfer_created_at'), table_name='transfer')
    op.drop_table('transfer')
    op.drop_index(op.f('ix_order_request_user_id'), table_name='order_request')
    op.drop_index(op.f('ix_order_request_created_at'), table_name='order_request')
    op.drop_index('ix_from_to_currency_count', table_name='order_request')
    op.drop_table('order_request')
    op.drop_index('ix_seller_buyer', table_name='order')
    op.drop_index(op.f('ix_order_to_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_from_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_created_at'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('currency')
    # ### end Alembic commands ###
