"""update settings

Revision ID: f9cf0e751a9e
Revises: 345597c5748f
Create Date: 2025-03-06 21:45:25.935019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cf0e751a9e'
down_revision = '345597c5748f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'commission_percent',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               nullable=False)
    op.alter_column('settings', 'prizm_rate_diff',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=2, asdecimal=False),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'prizm_rate_diff',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('settings', 'commission_percent',
               existing_type=sa.Numeric(precision=18, scale=2, asdecimal=False),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
